-- eLibrary Oracle schema
-- Run as the dedicated ELIBRARY database user.

CREATE TABLE E_BOOK (
  CALLNO VARCHAR2(100) CONSTRAINT E_BOOK_PK PRIMARY KEY,
  NAME VARCHAR2(200) NOT NULL,
  AUTHOR VARCHAR2(200) NOT NULL,
  PUBLISHER VARCHAR2(200) NOT NULL,
  QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
  ISSUED NUMBER(10) DEFAULT 0 NOT NULL,
  CONSTRAINT E_BOOK_QTY_CK CHECK (QUANTITY >= 0),
  CONSTRAINT E_BOOK_ISSUED_CK CHECK (ISSUED >= 0 AND ISSUED <= QUANTITY)
);

CREATE TABLE E_LIBRARIAN (
  ID NUMBER CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  PASSWORD VARCHAR2(400) NOT NULL,
  MOBILE NUMBER(10) NOT NULL,
  CONSTRAINT E_LIBRARIAN_EMAIL_UK UNIQUE (EMAIL)
);

CREATE SEQUENCE E_LIBRARIAN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE E_ISSUEBOOK (
  CALLNO VARCHAR2(100) NOT NULL,
  STUDENTID VARCHAR2(100) NOT NULL,
  STUDENTNAME VARCHAR2(100) NOT NULL,
  STUDENTMOBILE NUMBER(10) NOT NULL,
  ISSUEDDATE DATE DEFAULT SYSDATE NOT NULL,
  RETURNSTATUS VARCHAR2(10) DEFAULT 'no' NOT NULL,
  CONSTRAINT E_ISSUE_RETURN_CK CHECK (RETURNSTATUS IN ('yes','no')),
  CONSTRAINT E_ISSUE_BOOK_FK FOREIGN KEY (CALLNO) REFERENCES E_BOOK(CALLNO)
);

CREATE INDEX E_ISSUEBOOK_CALLNO_IDX ON E_ISSUEBOOK(CALLNO);
CREATE INDEX E_ISSUEBOOK_STUDENT_IDX ON E_ISSUEBOOK(STUDENTID);
